In [5]:
import pandas as pd
import numpy as np

In [6]:
data=pd.read_csv("E:\\Projects folder\\Iris\\Avela.csv",header=None)

In [7]:
data.head()

,0,1,2,3,4,5,6,7,8,9,10
0,0.266074,-0.165620,0.320980,0.483299,0.172340,0.273364,0.371178,0.929823,0.251173,0.159345,A
1,0.130292,0.870736,-3.210528,0.062493,0.261718,1.436060,1.465940,0.636203,0.282354,0.515587,A
2,-0.116585,0.069915,0.068476,-0.783147,0.261718,0.439463,-0.081827,-0.888236,-0.123005,0.582939,A
3,0.031541,0.297600,-3.210528,-0.583590,-0.721442,-0.307984,0.710932,1.051693,0.594169,-0.533994,A
4,0.229043,0.807926,-0.052442,0.082634,0.261718,0.148790,0.635431,0.051062,0.032902,-0.086652,F

In [8]:
data.columns = [' intercolumnar distance ','upper margin ','lower margin ','exploitation ','row number',
               'modular ratio ','interlinear spacing','weight ','peak number','mod_ratio','class']

In [9]:
data.head()

,intercolumnar distance,upper margin,lower margin,exploitation,row number,modular ratio,interlinear spacing,weight,peak number,mod_ratio,class
0,0.266074,-0.165620,0.320980,0.483299,0.172340,0.273364,0.371178,0.929823,0.251173,0.159345,A
1,0.130292,0.870736,-3.210528,0.062493,0.261718,1.436060,1.465940,0.636203,0.282354,0.515587,A
2,-0.116585,0.069915,0.068476,-0.783147,0.261718,0.439463,-0.081827,-0.888236,-0.123005,0.582939,A
3,0.031541,0.297600,-3.210528,-0.583590,-0.721442,-0.307984,0.710932,1.051693,0.594169,-0.533994,A
4,0.229043,0.807926,-0.052442,0.082634,0.261718,0.148790,0.635431,0.051062,0.032902,-0.086652,F

In [10]:
data['class'].value_counts()

A    4286
F    1961
E    1095
I     831
X     522
H     519
G     446
D     352
Y     266
C     103
W      44
B       5
Name: class, dtype: int64

In [11]:
data_shuffle=data.iloc[np.random.permutation(len(data))]
data=data_shuffle.reset_index(drop=True)
data.head()

,intercolumnar distance,upper margin,lower margin,exploitation,row number,modular ratio,interlinear spacing,weight,peak number,mod_ratio,class
0,-0.141273,-0.244132,0.249852,0.593729,0.261718,-0.474083,-0.006326,1.021425,0.095265,-0.308285,F
1,0.377169,0.164129,0.139604,-0.241825,0.172340,2.058932,0.559930,-1.806469,-1.089631,1.638727,A
2,-0.005490,-0.204876,0.320980,-0.694588,0.261718,-0.474083,-0.119577,-0.581395,-0.278912,-0.245429,F
3,0.648733,-0.197025,0.029355,0.335213,-0.185173,-1.346105,-0.987837,0.060828,0.469443,-0.605963,I
4,0.216699,0.321153,0.128935,0.491087,0.261718,0.439463,0.446679,0.230654,-0.278912,0.281223,A

In [12]:
data['class']=data['class'].map({'A':0,'F':1,'E':2,'I':3,'X':4,'H':5,'G':6,'D':7,'Y':8,'C':9,'W':10,'B':11})

data.head(20)

,intercolumnar distance,upper margin,lower margin,exploitation,row number,modular ratio,interlinear spacing,weight,peak number,mod_ratio,class
0,-0.141273,-0.244132,0.249852,0.593729,0.261718,-0.474083,-0.006326,1.021425,0.095265,-0.308285,1
1,0.377169,0.164129,0.139604,-0.241825,0.172340,2.058932,0.559930,-1.806469,-1.089631,1.638727,0
2,-0.005490,-0.204876,0.320980,-0.694588,0.261718,-0.474083,-0.119577,-0.581395,-0.278912,-0.245429,1
3,0.648733,-0.197025,0.029355,0.335213,-0.185173,-1.346105,-0.987837,0.060828,0.469443,-0.605963,3
4,0.216699,0.321153,0.128935,0.491087,0.261718,0.439463,0.446679,0.230654,-0.278912,0.281223,0
5,0.154980,-0.361900,0.409890,-0.171945,0.261718,-0.391033,0.031425,-0.347731,0.126447,-0.256376,1
6,0.117948,-0.212727,0.232070,0.807221,-1.078955,-0.017310,0.484429,-0.692199,-1.401445,-0.157222,0
7,0.093260,-0.055704,0.068476,0.305076,0.261718,-0.474083,0.597681,0.139848,0.469443,-0.624539,0
8,0.093260,-0.267686,0.168055,-0.383884,0.261718,0.771662,0.937434,-0.475270,0.313536,0.284839,0
9,0.624046,-2.426761,0.178724,0.711352,1.066121,-1.553729,-1.327590,1.860946,2.527420,-0.610796,3
10,0.006853,-0.055704,0.335206,1.778897,0.261718,0.107265,0.106925,0.834843,0.282354,0.163986,0
11,0.253730,0.219088,0.143160,0.720541,0.261718,0.564038,0.106925,0.111599,-0.029461,0.577080,0
12,0.130292,-0.275537,0.274747,-0.574878,0.261718,1.643684,0.597681,-1.791577,-1.682078,1.297772,0
13,0.068573,-0.204876,0.424116,1.412158,0.261718,-0.141884,2.371950,-0.224986,-0.871360,0.213183,0
14,-0.301743,0.195534,0.381439,0.351116,0.082961,1.186911,0.824183,-0.533420,0.625350,0.699608,2
15,-0.042522,-0.322644,0.310311,0.287293,0.261718,-1.096956,-0.006326,0.859034,0.064084,-0.883713,1
16,-2.523635,-0.346197,-2.349878,-0.775688,0.172340,-1.221530,0.031425,-2.818205,-1.307901,-1.009219,1
17,-0.030178,0.438921,-0.045329,0.766462,0.172340,0.564038,-0.195078,0.308995,0.407080,0.763813,0
18,0.377169,-0.079257,0.153829,-1.102952,0.261718,0.148790,0.522180,0.757782,-0.247731,-0.032150,0
19,0.475920,-0.338346,0.047137,-0.000972,0.976743,-0.141884,-0.912336,-0.258342,0.812439,0.554501,3

In [13]:
data_class = data['class'].values

In [14]:
pd.isnull(data).any()

 intercolumnar distance     False
upper margin                False
lower margin                False
exploitation                False
row number                  False
modular ratio               False
interlinear spacing         False
weight                      False
peak number                 False
mod_ratio                   False
class                       False
dtype: bool

In [15]:
from sklearn.model_selection import train_test_split
training_indices, validation_indices = training_indices, testing_indices = train_test_split(data.index,
                                                                                            stratify = data_class,
                                                                                            train_size=0.75, test_size=0.25)

In [16]:
training_indices.size, validation_indices.size

(7822, 2608)

In [ ]:
from tpot import TPOTClassifier
from tpot import TPOTRegressor

tpot = TPOTClassifier(generations=5,verbosity=2, population_size=20,
                      config_dict='TPOT MDR')

tpot.fit(data.drop('class',axis=1).loc[training_indices].values,
         data.loc[training_indices,'class'].values)

Warning: mdr.MDR is not available and will not be used by TPOT.
Warning: skrebate.MultiSURF is not available and will not be used by TPOT.
Warning: skrebate.ReliefF is not available and will not be used by TPOT.
Warning: skrebate.SURF is not available and will not be used by TPOT.
Warning: skrebate.SURFstar is not available and will not be used by TPOT.

HBox(children=(IntProgress(value=0, description='Optimization Progress', max=120, style=ProgressStyle(descript…

In [ ]:
tpot.score(data.drop('class',axis=1).loc[validation_indices].values,
           data.loc[validation_indices, 'class'].values)

In [ ]:
tpot = TPOTClassifier(verbosity=2, max_time_mins=2, max_eval_time_mins=0.04, population_size=15)
tpot.fit(data.drop('class',axis=1).loc[training_indices].values, data.loc[training_indices,'class'].values)

In [ ]:
tpot.score(data.drop('class',axis=1).loc[validation_indices].values,
           data.loc[validation_indices, 'class'].values)

In [ ]:
tpot = TPOTClassifier(verbosity=2, max_time_mins=2, max_eval_time_mins=0.04, population_size=20)
tpot.fit(data.drop('class',axis=1).loc[training_indices].values, data.loc[training_indices,'class'].values)

In [ ]:
tpot.score(data.drop('class',axis=1).loc[validation_indices].values,
           data.loc[validation_indices, 'class'].values)